### ISSUE TITLE
duplicate color modules: `SteamLog.h` and `Color.h`

### ISSUE THREAD

**Issue by tigercosmos** [ONNC/onnc#142]
The following two have a similar purpose:
- include/onnc/Diagnostic/StreamLog.h
- include/onnc/ADT/Color.h

We should merge the functions to just one place.
cc @a127a127  @poyenc  @LuisHsu

**Comment by poyenc** [comment]
To me, the `Color.h` is more like a utility to control what color do you want to apply on streaming text.  
And the Logger is one of Color users, which reuse Color codes.

**Comment by tigercosmos** [comment]
Yes, you are right. However what I am concerned about is,
It's obvious that the message in the snippet:

https://github.com/ONNC/onnc/blob/10a2dc10757cc977b3fc545374177b7c0bb6a530/tools/onnc/main.cpp#L98-L99

should use a function like `fatal()` in `SteamLog.h` rather than using `Color.h` by hand

**Comment by a127a127** [comment]
Yes, for the `onnc` `main.cpp` case, it should use `Diagnostic` rather than use `errs()`.

But the `Color.h` is still needed. The `StreamLog` is for `Diagnostic`, which is an infrastructure for Compiler error/warning messages. But not all messages are compiler error/warning message.

Does it make sense to you?

**Comment by tigercosmos** [comment]
No. I mean what we use `Color.h` to do can all be used by 'Diagnostic`. Actually `Diagnostic` is higher level than `Color`, which mean the developers should use the higher one.
But anyway, I don't think we are capable to refactor this part.
